package:
  name: oslo.middleware
  version: "1.0.0"

source:
  fn: oslo.middleware-1.0.0.tar.gz
  url: https://pypi.python.org/packages/source/o/oslo.middleware/oslo.middleware-1.0.0.tar.gz
  md5: 5102848f299c777e8333d207149e87ab
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - oslo.middleware = oslo.middleware:main
    #
    # Would create an entry point called oslo.middleware that calls oslo.middleware.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pbr

  run:
    - python
    - babel >=1.3
    - oslo.config >=1.9.0
    - oslo.context >=0.2.0
    - oslo.i18n >=1.3.0
    - six >=1.9.0
    - stevedore >=1.1.0
    - webob >=1.2.3

test:
  # Python imports
  imports:
    - oslo.middleware

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  #home: The package home page
  license: Apache Software License
  summary: 'Oslo Middleware library'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
